guid: 00b09d0100a85c82
video_mode: 800x600_yuv422
iso_speed: 400
frame_rate: 15
frame_id: pg1
camera_info_url: file:///home/meka/fuerte_workspace/sandbox/m3_cameras/config/pg1_800x600_calib.yml
#Right camera
# set some feature values:
#auto_gamma: 3           # Manual
#gamma: 2
#auto_shutter: 2         # Auto
#auto_white_balance: 2   # Auto
